config/routes.rb
Rails.application.routes.draw do
  resources :notes
  devise_for :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/", to:"notes#index" 
  root to:"notes#index" #had to define this so that the success/fail payment knows where to go
  get "/payments/success", to:"payments#success"

  post "/payments/webhook", to: "payments#webhook"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
    belongs_to :user
    validates :title, presence: true
    has_one_attached :picture
end

app/models/notebook.rb
class Notebook < ApplicationRecord
  belongs_to :user
  has_many :notes, dependent: :destroy
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notebooks_controller.rb
class NotebooksController < ApplicationController
  before_action :set_notebook, only: [:show, :edit, :update, :destroy]

  # GET /notebooks
  # GET /notebooks.json
  def index
    @notebooks = Notebook.all
  end

  # GET /notebooks/1
  # GET /notebooks/1.json
  def show
  end

  # GET /notebooks/new
  def new
    @notebook = Notebook.new
  end

  # GET /notebooks/1/edit
  def edit
  end

  # POST /notebooks
  # POST /notebooks.json
  def create
    @notebook = Notebook.new(notebook_params)

    respond_to do |format|
      if @notebook.save
        format.html { redirect_to @notebook, notice: 'Notebook was successfully created.' }
        format.json { render :show, status: :created, location: @notebook }
      else
        format.html { render :new }
        format.json { render json: @notebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notebooks/1
  # PATCH/PUT /notebooks/1.json
  def update
    respond_to do |format|
      if @notebook.update(notebook_params)
        format.html { redirect_to @notebook, notice: 'Notebook was successfully updated.' }
        format.json { render :show, status: :ok, location: @notebook }
      else
        format.html { render :edit }
        format.json { render json: @notebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notebooks/1
  # DELETE /notebooks/1.json
  def destroy
    @notebook.destroy
    respond_to do |format|
      format.html { redirect_to notebooks_url, notice: 'Notebook was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notebook
      @notebook = Notebook.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def notebook_params
      params.require(:notebook).permit(:title, :user_id, :note_id)
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user_listing, only: [:show, :edit, :update, :destroy]


  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  
    #this code in the show method is used to creatte the stripe session with all the relevant meta-data about the purchase
    session = Stripe::Checkout::Session.create(
        payment_method_types: ['card'],
        customer_email: current_user.email,
        line_items: [{
            name: @note.title,
            amount: 500, #this sets the price that will be charged
            currency: 'aud',
            quantity: 1,
        }],
        payment_intent_data: {
            metadata: {
                user_id: current_user.id,
                note_id: @note.id
            }
        },
        success_url: "#{root_url}payments/success?userID=#{current_user.id}&noteId=#{@note.id}",
        cancel_url: "#{root_url}"
    )

    @session_id = session.id
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    # @note = Note.new(note_params)
    @note=current_user.notes.create(note_params)
    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:title, :body, :picture)
    end

    def set_user_listing
      @note = current_user.notes.find_by_id(params[:id])
  
      if @note == nil
          redirect_to notes_path
      end
  end


end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
    skip_before_action :verify_authenticity_token, only: [:webhook]

    def success

    end

    def webhook

        #we're using a webhook to get stripe to send us a confirmation if our payment is a success. 
        #we install ultrahook so that we can target our localhost because our server is locally deployed

        p params


        ########this code caused 500 error, not sure ############
        # payment_id= params[:data][:object][:payment_intent]
        # payment = Stripe::PaymentIntent.retrieve(payment_id)
        # note_id = payment.metadata.note_id
        # user_id = payment.metadata.user_id

        # p "note id " + note_id
        # p "user id " + user_id

        # status 200
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notebooks_helper.rb
module NotebooksHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NotesOnRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>  
    <nav>
      <div class="button-container">
        <% if user_signed_in? %>
        <%= link_to "logout", destroy_user_session_path, method: :delete %>
        <% end %> 
      </div>
    </nav>
    <div class="devise-alerts">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <%= yield %>
  </body>
</html>

app/views/notebooks/_form.html.erb
<%= form_with(model: notebook, local: true) do |form| %>
  <% if notebook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notebook.errors.count, "error") %> prohibited this notebook from being saved:</h2>

      <ul>
        <% notebook.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :note_id %>
    <%= form.text_field :note_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/notebooks/edit.html.erb
<h1>Editing Notebook</h1>

<%= render 'form', notebook: @notebook %>

<%= link_to 'Show', @notebook %> |
<%= link_to 'Back', notebooks_path %>

app/views/notebooks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notebooks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>User</th>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notebooks.each do |notebook| %>
      <tr>
        <td><%= notebook.title %></td>
        <td><%= notebook.user.id %></td>
        <td><%= link_to 'Show', notebook %></td>
        <td><%= link_to 'Edit', edit_notebook_path(notebook) %></td>
        <td><%= link_to 'Destroy', notebook, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notebook', new_notebook_path %>

app/views/notebooks/new.html.erb
<h1>New Notebook</h1>

<%= render 'form', notebook: @notebook %>

<%= link_to 'Back', notebooks_path %>

app/views/notebooks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @notebook.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @notebook.user_id %>
</p>

<p>
  <strong>Note:</strong>
  <ul>
    <% for note in @notebook.notes %>
      <ul><%= note.title %></ul>
    <% end %>
  </ul>
 
</p>

<%= link_to 'Edit', edit_notebook_path(@notebook) %> |
<%= link_to 'Back', notebooks_path %>

app/views/notes/_form.html.erb
<%= form_with(model: note, local: true) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% note.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div>
  <%= form.label :picture %> <%= form.file_field :picture, accept:
  'image/png,image/gif,image/jpeg,image/jpg' %>
</div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<div class="formblock">
    <div class="formcontainer">
        <h1>Edit Note</h1>

        <%= render 'form', note: @note %>
        <div class="formblock-nav">
            <%= link_to 'Show', @note %> |
            <%= link_to 'Back', notes_path %>   
        </div>
    </div>
</div>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="homeheader">Notes</h1>



<div class="note-wrapper">
  <% current_user.notes.each do |note| %>
  <div class="card">
    <h1><%= note.title %></h1>
    <p><%= truncate(note.body, :length => 150, :separator => ' ') %></p>
    <div class="buttons">
      <%= link_to 'Show', note %>
      <%= link_to 'Edit', edit_note_path(note) %>
      <%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  </div>
  <% end %>
  
  <div class="card">
    <%= link_to '+ New note', new_note_path %>
  </div>

</div>

app/views/notes/new.html.erb
<div class="formblock">
    <div class="formcontainer">
        <h1>New Note</h1>

        <%= render 'form', note: @note %>

        <%= link_to 'Back', notes_path %>
    </div>
</div>

app/views/notes/show.html.erb
<div class="formblock">
  <%= link_to 'Back', notes_path %>
    <%= link_to 'Edit', edit_note_path(@note) %>
  <br>
    <button data-stripe="payment">
  Donate <%= number_to_currency(5) %>
</button>
</div>

<div class="showcontainer"> 

  <h1><%= @note.title %></h1>
  <hr>
  <p>
    <h3><%= @note.body %></h3>
  </p>
  <p>
    <%= image_tag @note.picture if @note.picture.attached? %>
  </p>

</div>

<%# need the below code to show the donate button and then link it up with javascsript %>


<script src="https://js.stripe.com/v3/"></script>

<script>
  document
    .querySelector("[data-stripe='payment']")
    .addEventListener("click", () => {
      const stripe = Stripe(
        "<%= Rails.application.credentials.dig(:stripe, :public_key) %>"
      );

      stripe.redirectToCheckout({
        sessionId: "<%= @session_id %>"
      });
    });
</script>

app/views/payments/success.html.erb
<div class="paymentsuccess">
    <h1>Thank you for your donation !</h1>
    <br> 
    <%= link_to "Back to notes", notes_path, class:"paymentback"%>
</div>